---
kind: pipeline
type: docker
name: gcc_build

steps:
  - name: lint
    image: vesoft/nebula-dev:ubuntu1804
    commands:
      - ln -snf $PWD/.linters/cpp/hooks/pre-commit.sh $PWD/.linters/cpp/pre-commit.sh
      - .linters/cpp/pre-commit.sh $(git --no-pager diff --diff-filter=d --name-only HEAD^ HEAD)

  - name: gcc_build
    image: vesoft/nebula-dev:ubuntu1804
    commands:
      - ./ci/test.sh
    depends_on:
      - lint

---
kind: pipeline
type: docker
name: clang_build

steps:
  - name: lint
    image: vesoft/nebula-dev:ubuntu1804
    commands:
      - ln -snf $PWD/.linters/cpp/hooks/pre-commit.sh $PWD/.linters/cpp/pre-commit.sh
      - .linters/cpp/pre-commit.sh $(git --no-pager diff --diff-filter=d --name-only HEAD^ HEAD)

  - name: clang_build
    image: vesoft/nebula-dev:ubuntu1804
    commands:
      - ./ci/test.sh prepare
      - ./ci/test.sh clang
      - ./ci/test.sh test
    depends_on:
      - lint
