meta_nodes:
  - addrs: "192.168.0.2:65500"
    root: "/usr/local/nebula/"
    data: "/usr/local/nebula/data/meta"
    user: "nebula"
  - addrs: "192.168.0.3:65500"
    root: "/usr/local/nebula/"
    data: "/usr/local/nebula/data/meta"
    user: "nebula"
  - addrs: "192.168.0.4:62500"
    root: "/usr/local/nebula/"
    data: "/usr/local/nebula/data/meta"
    user: "nebula"

storage_nodes:
  - addrs: "192.168.0.2:44500"
    root: "/usr/local/nebula/"
    data: "/usr/local/nebula/data/storage"
    user: "nebula"
  - addrs: "192.168.0.3:44510"
    root: "/usr/local/nebula/"
    data: "/usr/local/nebula/data/storage"
    user: "nebula"
  - addrs: "192.168.0.4:44520"
    root: "/usr/local/nebula/"
    data: "/usr/local/nebula/data/storage"
    user: "nebula"
max_ssh_connections: 10
backend: "s3://nebulabackup"
space_names: ["nba"]

