name: docker

on:
  push:
    branches:
      - 'v[0-9]+.*'
  schedule:
    - cron: '0 18 * * *'

jobs:
  docker:
    name: build docker image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - metad
          - storaged
          - tools
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - id: tag
        run: |
          TAG="v2-nightly"
          BRANCH="master"
          if ${{ github.event_name == 'push' }}; then
            TAG=$(echo "${{ github.ref }}" | tr / ' ' | cut -d ' ' -f 3)
            BRANCH=$TAG
          fi
          echo "::set-output name=TAG::$TAG"
          echo "::set-output name=BRANCH::$BRANCH"
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: vesoft/nebula-${{ matrix.service }}
          tags: ${{ steps.tag.outputs.TAG }}
          dockerfile: docker/Dockerfile.${{ matrix.service }}
          cache_froms: vesoft/nebula-dev:centos7
          add_git_labels: true
          build_args: BRANCH=${{ steps.tag.outputs.BRANCH }}
