name: docker

on:
  schedule:
    - cron: '0 18 * * *'

jobs:
  docker:
    name: build docker image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - metad
          - storaged
          - tools
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: vesoft/nebula-${{ matrix.service }}
          tags: v2-nightly
          dockerfile: docker/Dockerfile.${{ matrix.service }}
          cache_froms: vesoft/nebula-dev:centos7
          add_git_labels: true
